# Generated by Django 3.0.3 on 2020-05-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200506_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='price',
            new_name='amount',
        ),
    ]
