# Generated by Django 3.0.3 on 2020-05-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200506_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='total_price',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='transit_price',
            new_name='transit_amount',
        ),
    ]
