# Generated by Django 3.0.3 on 2020-05-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200506_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='amount',
            new_name='price',
        ),
    ]
